theme = "monokai_pro_ristretto"

[editor]
mouse = true
# end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 3000

[editor.soft-wrap]
enable = true

[editor.lsp]
# display-inlay-hints = true
# display-messages = true (true is default)

[keys.normal]
"C-f" = ":run-shell-command tmux neww tmux-sessionizer"
"S-tab" = "jump_backward"
x = "select_line_below"
X = "select_line_above"

# lazygit
C-g = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
]

# scooter integrxation
C-r = [
  ":write-all",
  ":insert-output scooter --no-stdin >/dev/tty",
  ":redraw",
  ":reload-all",
]

[editor.indent-guides]
render = true


# yazi
[keys.normal.space]
e = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-h21a434",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":redraw",
  ':set mouse false',
  ':set mouse true',
]
