theme = "monokai_pro_ristretto"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 3000

[editor.soft-wrap]
enable = true

[keys.normal]
"C-f" = ":run-shell-command tmux neww tmux-sessionizer"
"S-tab" = "jump_backward"
x = "select_line_below"
X = "select_line_above"
C-g = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
] # lazygit
[editor.indent-guides]
render = true

[keys.select.ret]
# scooter integration
s = [
  ":write-all",
  ":insert-output scooter --no-stdin >/dev/tty",
  ":redraw",
  ":reload-all",
]
